version: "3.8"

services:
  outline:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/var/lib/outline/data
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_COLLABORATION_URL: ${REDIS_COLLABORATION_URL}
      COLLABORATION_URL: ${COLLABORATION_URL}
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
    command: ["yarn", "start"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
