variable "project_name" {}
variable "aws_region" {}
variable "vpc_cidr" {}
variable "public_subnet_1_cidr" {}
variable "public_subnet_2_cidr" {}
variable "public_subnet_1_az" {}
variable "public_subnet_2_az" {}
variable "private_subnet_1_cidr" {}
variable "private_subnet_2_cidr" {}
variable "private_subnet_1_az" {}
variable "private_subnet_2_az" {}
variable "domain_name" {}
variable "record_name" {}
variable "ecr_image_url" {}
variable "task_cpu" {}
variable "task_memory" {}
variable "containerPort" {}
variable "ecs_task_deployment_minimum_healthy_percent" {}
variable "ecs_task_deployment_maximum_percent" {}
variable "admin_user_arn" {}
variable "db_username" {}
variable "db_password" {}
variable "rds_endpoint" {}
variable "redis_endpoint" {}
variable "secret_key" {}
variable "utils_secret" {}
