name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type 'DESTROY' to confirm apply"
        required: true
jobs:
  terraform-destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm_destroy == 'DESTROY' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Download terraform.tfvars from S3
        run: aws s3 cp s3://outline-terraform-config/terraform.tfvars ./terraform/terraform.tfvars

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false -reconfigure

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve -input=false
